hydra:
  searchpath:
    - file://verl/trainer/config

defaults:
  - ppo_megatron_trainer
  - _self_

algorithm:
  adv_estimator: grpo
  use_kl_in_reward: false

data:
  train_files: /from_s3/dataset/train.parquet
  val_files: /from_s3/dataset/test.parquet
  train_batch_size: 128
  max_prompt_length: 512
  max_response_length: 2048
  filter_overlong_prompts: true
  truncation: error
  return_raw_chat: true

actor_rollout_ref:
  model:
    path: /from_s3/models
    use_fused_kernels: false # true
    use_remove_padding: false
    trust_remote_code: true

  actor:
    use_dynamic_bsz: false
    ppo_max_token_len_per_gpu: 2048
    ppo_mini_batch_size: 16
    ppo_micro_batch_size_per_gpu: 1
    optim:
      lr: 1e-6
    use_kl_loss: false
    kl_loss_coef: 0.001
    kl_loss_type: low_var_kl
    entropy_coeff: 0

    # USE_LEGACY_WORKER_IMPL=enable path from the bash snippet
    router_replay:
      # mode: R3
      mode: disabled
      record_file: null  # Path for recording routing decisions
      replay_file: null   # Path for replaying recorded decisions

    megatron:
      param_offload: true
      optimizer_offload: true
      grad_offload: true
      pipeline_model_parallel_size: 1
      # tensor_model_parallel_size: 4
      # expert_model_parallel_size: 4
      # expert_tensor_parallel_size: 2

      tensor_model_parallel_size: 1
      expert_model_parallel_size: 1
      expert_tensor_parallel_size: 1

      use_mbridge: true
      override_transformer_config:
        # moe_enable_deepep: true
        # moe_token_dispatcher_type: flex
        apply_rope_fusion: false # true
        bias_activation_fusion: false # true
        # moe_router_dtype: fp32
        recompute_method: uniform
        recompute_granularity: full
        recompute_num_layers: 1
        gradient_accumulation_fusion: false # true
        moe_permute_fusion: false

#  Using a large number of experts (e.g. >=32) without fp32 routing. Consider enabling moe_router_dtype for better numerical stability. [repeated 7x across cluster]
# UserWarning: moe_enable_deepep is deprecated.Please use --moe-flex-dispatcher-backend=deepep instead. [repeated 7x across cluster]

  rollout:
    name: vllm
    mode: async
    temperature: 1.0
    tensor_model_parallel_size: 1
    gpu_memory_utilization: 0.75
    n: 8

    enable_chunked_prefill: true # not tested yet with true
    enable_prefix_caching: true # not tested yet with true
    enforce_eager: false # not tested yet with false

    max_num_batched_tokens: 1024
    skip_tokenizer_init: true
    enable_rollout_routing_replay: false # not tested yet with true
    log_prob_use_dynamic_bsz: false
    log_prob_micro_batch_size_per_gpu: 1
    log_prob_max_token_len_per_gpu: 2048

    load_format: "safetensors"

    disable_log_stats: false
    prometheus:
      enable: true

    speculative_decoding:
      enable: true

      method: EAGLE3

      num_steps: 1
      num_draft_tokens: 4

      draft_model_path: /from_s3/eagle_vllm
      draft_tensor_parallel_size: 1


trainer:
  critic_warmup: 0
  logger: ["console", "clearml"]
  project_name: verl_megatron_moe
  experiment_name: cuda-graphs-eagle3-4tokens-qwen3-lighteval-MATH
  nnodes: 1
  n_gpus_per_node: 8
  save_freq: -1
  test_freq: 10
  total_training_steps: 50000
  balance_batch: false
  use_legacy_worker_impl: enable
  val_before_train: false
  log_val_generations: 10
  # rollout_data_dir: /from_s3/train_rollout_data/
